### ISSUE TITLE
ICE Adapter accepts only a single RPC Connection

### ISSUE THREAD

**Issue by HurricanKai** [FAForever/java-ice-adapter#20]
I'm not sure if this is intended, there is documentation on how to connect to ICE, so I assumed that I was allowed to connect to the adapter, to poll various information about the Game, and the current state.
But it looks like the Code only accepts one RPC Connection, which makes sense, since it can be assumed that this is the one that should manage the connection (as in, if that one is lost, the Game should close), but for some reason others aren't accepted after that, only that first "master" connection is ever accepted. Is this a bug, or intentional?

**Comment by Geosearchef** [comment]
This is intentional. It could accept more connections and allow them to control the adapter, but I don't see a reason to. It's just for the faf client communicating with the adapter and therefore the adapter communicating with the server.

What do you need this for? What do you want to do? Maybe we can help you with that.

**Comment by HurricanKai** [comment]
I'm just interested in Experimenting with GPGNet & potentially Ice messages for the sake of it, wanted to lookup how (if) the adapter parses GPGNet messages, then stumbled across the Readme.
